### ISSUE TITLE
I want to talk to you

### ISSUE THREAD

**Issue by Tonyjr7** [byteballet/byteballet#1]
Hi, @byteballet.

**Comment by kamaalsultan** [comment]
Hi, @Tonyjr7

**Comment by Tonyjr7** [comment]
Yeah
Can you tell me about your coding backgrounds
Cos I see you have a lot of codes

**Comment by kamaalsultan** [comment]
Yes, I have 8 years of professional experience in software development.

**Comment by Tonyjr7** [comment]
Wow
That's Great
Can we have a quick call
Cos am looking to hire someone like you

**Comment by kamaalsultan** [comment]
You can introduce yourself first.

**Comment by Tonyjr7** [comment]
My name is Harry James
A hiring manager at Dream Wave Inc
So where can we talk better, Google meet, discord, WhatsApp

**Comment by kamaalsultan** [comment]
Google meet is preferred.

**Comment by kamaalsultan** [comment]
Also discord is available but for text. crunch_56641

**Comment by Tonyjr7** [comment]
Okay
I sent you a friend request on discord
Smart ai

**Comment by Tonyjr7** [comment]
You shouldn't block me
